version: '3.7'

services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    restart: on-failure
    init: true
    ports:
      - 5432:5432
    volumes:
      - ./pg_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: typeorm
      POSTGRES_PASSWORD: plaintextpassword
      POSTGRES_MULTIPLE_DATABASES: typeorm
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U typeorm']
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s
