version: '3.7'

services:
  typeorm_template:
    image: postgres:10-alpine
    container_name: typeorm_template
    restart: on-failure
    init: true
    ports:
      - 5432:5432
    volumes:
      - typeorm_template:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: typeorm
      POSTGRES_PASSWORD: plaintextpassword
      POSTGRES_MULTIPLE_DATABASES: typeorm
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '10'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U typeorm']
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  typeorm_template:
